### PR TITLE
Initial commit: janaf tables and Jupyter notebooks

### PR DESCRIPTION
**Pull request by decaluwe**
- Calcualte adiabatic flame temp 'manually,' using JANAF, assuming
constant (average) Cp, and assuming complete combustion.
- Extension workbook added, using JANAF to find exact enthalpies at T_2.

### CODE REVIEW

**Comment by decaluwe** [comment]
@bryanwweber are you the only one with write access, here?  Can you and/or @rwest give this a quick look, particularly w/r/t level of detail?  There is currently a lot of background info on what an adiabatic flame temp calc looks like, but I think it's mostly necessary...

**Comment by speth** [comment]
I changed the permissions for this repository so that @Cantera/members has "maintainer" access, which includes write permissions.

**Comment by bryanwweber** [comment]
@decaluwe I'm looking through this now, I'll push an update later this morning.

**Comment by rwest** [comment]
These days I prefer using f-strings, so
```python
print('The heat of reaction is {:.2f} kJ/mol.'.format(q_rxn))
```
would become
```python
print(f'The heat of reaction is {q_rxn:.2f} kJ/mol.')
```
Can we assume everyone is on Python 3.6+ ?

**Comment by rwest** [comment]
It annoys me when students do `32.697*10**(-3)`  instead of `32.697e-3`, and I feel they should be exposed to the (read: "my") preferred way of doing it as early and often as possible.

**Comment by bryanwweber** [comment]
@rwest I'm making both of those changes in my updates 😄

> It annoys me when students do `32.697*10**(-3)` instead of `32.697e-3`, and I feel they should be exposed to the (read: "my") preferred way of doing it as early and often as possible.

I think your preferred method (which is also mine) is also _technically_ better. The former method involves floating point arithmetic, and so a loss of precision during that calculation, plus the loss of precision of creating the float `32.697`. The latter method only loses precision when assigning the number.

**Comment by rwest** [comment]
👍🏻 That suspicion why I decided not to make the changes myself, as merging Jupyter diffs is still a pain in git.

**Comment by bryanwweber** [comment]
Right, so since you're working on your `main` branch, it's a pain for me to push any updates. I've created #2 on the `2021-ncm` branch in my fork. Feel free to push any updates to that branch. For reference, the procedure (I'm pretty sure) is:

```
git remote add bryanwweber https://github.com/bryanwweber/workshop-materials.git
git fetch bryanwweber
git checkout --track bryanwweber/2021-ncm
```

After that, just `git push` should be enough to add changes to that branch.

**Pull request closed without merging**
