### PR TITLE
Materials for 2021 NCM

### PR DESCRIPTION
**Pull request by bryanwweber**
Supersedes #1

### CODE REVIEW

**Comment by bryanwweber** [comment]
@decaluwe I made a few changes from your last update:

1. I split each "step" into its own Notebook
2. I (hope I) clarified the thermo for the adiabatic flame temperature
3. I flipped the sign of `q_rxn`, so it matched the equations
4. I added the `mhchem` package, which includes the `\ce` macro to set chemical equations. There's a Markdown cell at the very top of each Notebook that adds the `mhchem`, it's only got that content though so you can't see it unless you edit it.
5. I switched everything to double quotes and `f`-strings
6. I simplified some of the discussion around Cantera objects, etc. to get to the calculations faster

Let me know what you think!

**Comment by decaluwe** [comment]
Thanks. I like these changes!

> I split each "step" into its own Notebook

Lol, I thought the explicit commentary on the outline doc, after I suggested multiple notebooks, was "make it all one notebook?" Separate notebooks is certainly my  preference, but I'm getting vertigo, here. 😂 

Two thoughts:
1. Do we want the background on adiabatic flame temperatures in the header for *every* notebook?  I think we can assume we are going through these sequentially.  Maybe add a note to the top of each subsequent notebook pointing them back to the first, if they want to review the theory, if we're concerned?

2. Very minor, but: your edit to the very last line of the "full combustion in Cantera" notebook reads better than the original, but is less correct:  The N2 mole fraction is exactly the same, not nearly constant, due to both being inert and the moles of reactants being equal to the moles of product (both conditions together guarantee that it is exactly unchanged; drop either one and it would change).

How about something like this?
>As expected, the $\ce{N2}$  mole fraction is constant, since $\ce{N2}$ is inert and the moles of reactants consumed equals the moles of products created, for this reaction.

**Comment by bryanwweber** [comment]
> after I suggested multiple notebooks

Ah, I interpreted this suggestion as one Notebook with the answers, and one Notebook that was blank, which I still think is a bad idea 😉 My mistake!

> 1. Do we want the background on adiabatic flame temperatures in the header for _every_ notebook?  I think we can assume we are going through these sequentially.

My intention was to make the content a little bit evergreen, in the sense that someone who finds this after the workshop, and who did not attend, can pick up at any Notebook and have the same background. A link would probably work just as well though. Might as well take advantage of what the web gives us...


> The N2 mole fraction is exactly the same, not nearly constant,

FWIW, I get very slight differences in the mole fraction of N2, probably due to the numerical solution.

```python
In [1]: import cantera as ct

In [2]: gas = ct.Solution("input-files/methane.yaml")

In [3]: gas.TPX = 298.15, ct.one_atm, "CH4:1, O2:2, N2:7.52"

In [4]: gas.mole_fraction_dict()
Out[4]:
{'CH4': 0.09505703422053231,
 'N2': 0.714828897338403,
 'O2': 0.19011406844106463}

In [5]: X_1 = gas.X

In [6]: gas.equilibrate("hp")

In [7]: X_2 = gas.X

In [8]: X_1 - X_2
Out[8]:
array([ 9.50569254e-02,  1.90113851e-01, -1.90113851e-01,  1.27853284e-12,
       -9.50569254e-02])

In [9]: gas.mole_fraction_dict()
Out[9]:
{'CH4': 1.0881481470135891e-07,
 'CO2': 0.09505692540339462,
 'H2O': 0.1901138508145434,
 'N2': 0.7148288973371245,
 'O2': 2.176301227971112e-07}
```

**Comment by decaluwe** [comment]
Oh, odd.  I made sure to check it, before running my mouth off.  Using the "one big notebook", subtracting X_N2 init from final returned `[0.]`.  Hmm 🤔

Edit: ah, nevermind: I was going back and retrieving my `X_init` on the _still equilibrated_ state, without first re-initializing it.

Odd to me that element conservation has a tolerance on it, at all.  But I guess while strict element balance can be done in a straightforward manner for a small problem like this, it's not really feasible (or at least worth the considerable effort) for a larger problem.

**Comment by bryanwweber** [comment]
> Odd to me that element conservation has a tolerance on it, at all.

Any finite-precision algorithm has to have some tolerance above zero. Any changes of the numbers below machine precision are meaningless anyways.

**Pull request merged**
